# Site settings
title: KietNVT
email: kietdev38@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blogs!
  Stay Hungry. Stay Foolish.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tuankiet.github.io"
twitter_username: nvtkiet
github_username:  tuankiet

# Build settings
markdown: kramdown

# Gems
gems: [jekyll-paginate]
paginate: 5
