# Site settings
title: KietNVT
home: Home
sitename: Welcome to my blogs! Stay Hungry. Stay Foolish.
contact_me: Contact
email: kietnvt.it@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blogs!
  Stay Hungry. Stay Foolish.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tuankiet.github.io"
twitter_username: nvtkiet
github_username:  tuankiet

# Build settings
markdown: kramdown

# Gems
gems: [jekyll-paginate]
paginate: 5

theme: jekyll-theme-hacker

github:
  repository_url: https://github.com/tuankiet/tuankiet.github.io