# Site settings
title: "Welcome You :)"
description: "a blog of one ruby on rails developer."
sub_description: "I am Kiet"
email: "kietnvt.it@gmail.com"
url: "https://tuankiet.github.io"
twitter_username: "nvtkiet"
github_username:  "tuankiet"

# Header Links
github:
  is_project_page: true
  repository_name: "Blog"
  project_tagline: "Blog"
  github_profile: "https://github.com/tuankiet"
  repository_url: "https://github.com/tuankiet/tuankiet.github.io"
  owner_name: "Tuan Kiet"

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-paginate
  - jemoji

paginate: 10
paginate_path: "/blog/page:num/"

theme: jekyll-theme-architect

